/*
Channel API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InboundMessageMetadata } from './inbound-message-metadata';
import { InboundMessageSender } from './inbound-message-sender';

/**
 * 
 * @export
 * @interface InboundMessage
 */
export interface InboundMessage {
    /**
     * 
     * @type {InboundMessageSender}
     * @memberof InboundMessage
     */
    'sender': InboundMessageSender;
    /**
     * Subject of the message
     * @type {string}
     * @memberof InboundMessage
     */
    'subject'?: string;
    /**
     * Body of the message
     * @type {string}
     * @memberof InboundMessage
     */
    'body': string;
    /**
     * 
     * @type {InboundMessageMetadata}
     * @memberof InboundMessage
     */
    'metadata': InboundMessageMetadata;
    /**
     * Time in seconds at which message was created in external system
     * @type {number}
     * @memberof InboundMessage
     */
    'delivered_at'?: number;
    /**
     * Binary data of attached files. Must use `Content-Type: multipart/form-data` if specified. See [example](https://gist.github.com/hdornier/e04d04921032e98271f46ff8a539a4cb) or read more about [Attachments](https://dev.frontapp.com/docs/attachments-1).  Max 25 MB.
     * @type {Array<Uint8Array | File | buffer.File>}
     * @memberof InboundMessage
     */
    'attachments'?: Array<Uint8Array | File | buffer.File>;
}

