/*
Channel API

Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.

With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InboundMessageMetadata } from './inbound-message-metadata';
import { OutboundMessageToInner } from './outbound-message-to-inner';

/**
 * Payload to receive an outbound message from an external system into Front.
 * @export
 * @interface OutboundMessage
 */
export interface OutboundMessage {
    /**
     * Name of the sender
     * @type {string}
     * @memberof OutboundMessage
     */
    'sender_name'?: string;
    /**
     * Data of the message recipient
     * @type {Array<OutboundMessageToInner>}
     * @memberof OutboundMessage
     */
    'to': Array<OutboundMessageToInner>;
    /**
     * Subject of the message
     * @type {string}
     * @memberof OutboundMessage
     */
    'subject'?: string;
    /**
     * ID of the teammate on behalf of whom the message is sent
     * @type {string}
     * @memberof OutboundMessage
     */
    'author_id'?: string;
    /**
     * Body of the message
     * @type {string}
     * @memberof OutboundMessage
     */
    'body': string;
    /**
     * 
     * @type {InboundMessageMetadata}
     * @memberof OutboundMessage
     */
    'metadata': InboundMessageMetadata;
    /**
     * Time in seconds at which message was created in external system
     * @type {number}
     * @memberof OutboundMessage
     */
    'delivered_at'?: number;
    /**
     * Binary data of attached files. Must use `Content-Type: multipart/form-data` if specified. See [example](https://gist.github.com/hdornier/e04d04921032e98271f46ff8a539a4cb) or read more about [Attachments](https://dev.frontapp.com/docs/attachments-1).  Max 25 MB.
     * @type {Array<Uint8Array | File | buffer.File>}
     * @memberof OutboundMessage
     */
    'attachments'?: Array<Uint8Array | File | buffer.File>;
}

